### ISSUE TITLE
Windows 10 下编译出错

### ISSUE THREAD

**Issue by csdlee** [huntlabs/dredis#3]
Error: none of the overloads of `getOption`  are callable using argument types `(SocketOptionLevel, SocketOption, int)`, candidates are:                                            C:\D\dmd2\windows\bin\..\..\src\phobos\std\socket.d(3133,9):        `std.socket.Socket.getOption(SocketOptionLevel level, SocketOption  option, void[] result)`                                                                                                                 C:\D\dmd2\windows\bin\..\..\src\phobos\std\socket.d(3143,9):        `std.socket.Socket.getOption(SocketOptionLevel level, SocketOption  option, out __c_long result)`                                                                                                           C:\D\dmd2\windows\bin\..\..\src\phobos\std\socket.d(3150,9):        `std.socket.Socket.getOption(SocketOptionLevel level, SocketOption  option, out Linger result)`                                                                                                             C:\D\dmd2\windows\bin\..\..\src\phobos\std\socket.d(3157,10):        `std.socket.Socket.getOption(SocketOptionLevel level, SocketOption  option, out Duration result)`                                                                                                          FAIL C:\Users\xdao\AppData\Local\dub\packages\dredis-0.0.9\dredis\.dub\build\library-debug-windows-x86-dmd_2083-186DE7EBDCDB87A28A024C 3287AB26BC\ dredis staticLibrary                                                                                                        C:\D\dmd2\windows\bin\dmd.exe failed with exit code 1.
--dmd 2.083

**Comment by Heromyth** [comment]
Fixed by https://github.com/huntlabs/dredis/commit/20dd3613dc5f1f7b08e72d980f67b7e7b14cf49a
